version: "3.8"

services:
  todoapp:
    build: .
    container_name: django_docker_compose
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  redis:
    image: redis/redis-stack
    restart: always
    container_name: redis

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    depends_on:
      - redis
      - todoapp
    container_name: celery
  
  
 
