# Generated by Django 4.0.6 on 2022-08-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_aproove',
            new_name='is_email_verified',
        ),
    ]
