# Generated by Django 4.0.6 on 2022-08-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_remove_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
