# Generated by Django 4.0.6 on 2022-08-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-importance', 'deadline_date'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачі'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline_date',
            field=models.CharField(max_length=10, verbose_name='Дата дедлайну'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(max_length=350, verbose_name='Опис задачі'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='importance',
            field=models.BooleanField(verbose_name='Важливість'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(default='', max_length=10, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва задачі'),
        ),
    ]
