# Generated by Django 4.0.6 on 2022-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('in_progress', 'in_progress'), ('blocked', 'blocked'), ('finished', 'finished')], default='todo', max_length=20, verbose_name='Статус'),
        ),
    ]
