# Generated by Django 4.0.6 on 2022-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasks_author_alter_tasks_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='finished_task',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
