# Generated by Django 4.0.6 on 2022-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasks_finished_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finished_task',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
