# Generated by Django 4.0.6 on 2022-08-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasks_finished_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='in_progress_task',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
